services:
  database:
    container_name: database
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ${DATABASE_DATA_PATH}/${PROJECT_NAME}/${DATABASE_NAME}/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    volumes:
      - .:/usr/src/mytable
      - /usr/src/mytable/node_modules
      - /usr/src/mytable/apps/server/node_modules
    ports:
      - ${SERVER_PORT}:3000
    working_dir: '/usr/src/mytable/apps/server'
    # command: sh -c 'yarn prisma migrate dev && yarn start:dev'
    command: yarn start:dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}?schema=public
    depends_on:
      - database

  # client-next:
  #   container_name: client-next
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: deps
  #   volumes:
  #     - ./:/usr/src/mytable
  #     - /usr/src/mytable/node_modules
  #     - /usr/src/mytable/apps/client/node_modules
  #   ports:
  #     - 4001:4001
  #   command: yarn client:web:dev
  #   depends_on:
  #     - server
  #   env_file:
  #     - .env

  # client-expo:
  #   container_name: client-expo
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: deps
  #   volumes:
  #     - ./:/usr/src/mytable
  #     - /usr/src/mytable/node_modules
  #     - /usr/src/mytable/apps/client/node_modules
  #   ports:
  #     - 19001:19001
  #     - 19002:19002
  #   command: yarn client:expo:dev
  #   depends_on:
  #     - server
  #   env_file:
  #     - .env

  # restaurant-next:
  #   container_name: restaurant-next
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: deps
  #   volumes:
  #     - ./:/usr/src/mytable
  #     - /usr/src/mytable/node_modules
  #     - /usr/src/mytable/apps/restaurant/node_modules
  #   ports:
  #     - 4000:4000
  #   command: sh -c "yarn restaurant:web:dev"
  #   depends_on:
  #     - server
  #   env_file:
  #     - .env

  # restaurant-expo:
  #   container_name: restaurant-expo
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: deps
  #   volumes:
  #     - ./:/usr/src/mytable
  #     - /usr/src/mytable/node_modules
  #     - /usr/src/mytable/apps/restaurant/node_modules
  #   ports:
  #     - 19000:19000
  #     - 19003:19003
  #   command: yarn restaurant:expo:dev
  #   depends_on:
  #     - server
  #   env_file:
  #     - .env

  # dba:
  #   container_name: prisma-studio
  #   image: timothyjmiller/prisma-studio
  #   env_file:
  #     - .env
  #   ports:
  #     - ${PRISMA_STUDIO_PORT}:5555
  #   depends_on:
  #     - db
