import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';
import { Prisma } from '@prisma/client';

export class CreateClientDto implements Prisma.ClientCreateInput {
  @ApiProperty({ example: 'Gabriel' })
  name: string;

  @ApiProperty({ example: 'Alves' })
  surname: string;

  @ApiProperty({ example: '(99) 99999-9999' })
  phone: string;

  @ApiProperty({ example: 'your@email.com' })
  email: string;

  @ApiProperty({ example: '123.456.789-09' })
  cpf: string;

  @ApiHideProperty()
  // autogenerated
  identifier?: string;
}
